# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"IN_COLAB": "00_core.ipynb",
         "setup_git": "00_core.ipynb",
         "git_push": "00_core.ipynb",
         "setup_project": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pete88b.github.io/nbdev_colab_helper/"

git_url = "https://github.com/pete88b/nbdev_colab_helper/tree/master/"

def custom_doc_links(name): return None
